"""interview 添加 pending

Revision ID: 9be14c1dabdb
Revises: dfdb60dd20ef
Create Date: 2026-09-16 21:01:54.615590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be14c1dabdb'
down_revision: Union[str, Sequence[str], None] = 'dfdb60dd20ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
